[package]
name = "packall"
version = "0.3.3"
authors = ["Éverton M. Vieira <everton.muvi@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
serde_json = "1.0"
crossbeam = "0.8"
crossbeam-channel = "0.5"
sha2 = "0.9"
rand = "0.8"
unicase = "2.6"
