use clap::{Command, Arg, ArgMatches};

pub fn parse() -> ArgMatches {
    Command::new("Packall")
        .version(clap::crate_version!())
        .about("Packall is a command program that eats all the files you feed and keeps them organized, first in the belly, then in the body (indexed), for future searches.")
        .author("Éverton M. Vieira <everton.muvi@gmail.com>")
        .arg(
            Arg::new("body")
                .short('b')
                .long("body")
                .value_name("DIR")
                .takes_value(true)
                .required(true)
                .help("Where all books I eat ends up")
        )
        .arg(
            Arg::new("speed")
                .short('e')
                .long("speed")
                .value_name("NUMBER")
                .default_value("4")
                .takes_value(true)
                .required(false)
                .help("How fast should I go")
        )
        .arg(
            Arg::new("clean")
                .short('c')
                .long("clean")
                .takes_value(false)
                .required(false)
                .help("Removes from the origin and/or the already digested.")
        )
        .arg(
            Arg::new("feed")
                .short('f')
                .long("feed")
                .value_name("PATH")
                .takes_value(true)
                .required(false)
                .help("Yami! More files for me to eat")
        )
        .arg(
            Arg::new("digest")
                .short('d')
                .long("digest")
                .takes_value(false)
                .required(false)
                .help("Digests the food in my belly")
        )
        .arg(
            Arg::new("search")
                .short('s')
                .long("search")
                .value_name("WORDS")
                .takes_value(true)
                .required(false)
                .help("Searches in the digested words")
        )
        .arg(
            Arg::new("lend")
                .short('l')
                .long("lend")
                .value_name("PATH")
                .takes_value(true)
                .required(false)
                .help("Copies the founds inside me")
        )
        .arg(
            Arg::new("give")
                .short('g')
                .long("give")
                .value_name("PATH")
                .takes_value(true)
                .required(false)
                .help("Moves the founds inside me")
        )
        .arg(
            Arg::new("junk")
                .short('j')
                .long("junk")
                .takes_value(false)
                .required(false)
                .help("Discards the founds inside me")
        )
        .arg(
            Arg::new("open")
                .short('o')
                .long("open")
                .takes_value(false)
                .required(false)
                .help("Opens the founds inside me")
        )
        .get_matches()
}
